### ISSUE TITLE
Reveal is not correct showing on api level 17

### ISSUE THREAD

**Issue by liufuxin** [Yalantis/Euclid#2]
On emulator nexus s the Reveal animation is not correct,show a RectReveal not a CircularReveal ,But when run the Slide-Menu depends on Ozodrukh's animation util for CircularReveal animation is correct on the same level emulator.

Is that a Os problem?

**Comment by shliama** [comment]
@liufuxin Thanks for report. I'm going to take a look at this bug this week. Not sure when, but till the end of the week I'll post an update here.

**Comment by shliama** [comment]
@liufuxin ok, so I've checked this on genymotion emulator Nexus 4 with API 17 and successfully reproduced this bug. Also I've reproduced the same bug in Slide-Menu app :) Not sure yet, is it genymotion issue or bug of android 4.2 or both...
I'm going to try to reproduce the bug on real device with android 4.2 on Monday, and post update here.

**Comment by liufuxin** [comment]
@shliama I've checked this on real device with android 4.2.1,the animation shows the correct in Slide-Menu app,but not in Euclid.

**Comment by shliama** [comment]
@liufuxin indeed. I've double-checked this on real device too and reproduced bug with this library and this one [https://github.com/Yalantis/Side-Menu.Android]. 
They both depends on this library [https://github.com/ozodrukh/CircularReveal] to make circle reveal animation. Also I've found this issue [https://github.com/ozodrukh/CircularReveal/issues/11] in which said that this bug is due to hardware acceleration. As you can see, it's not seems to be fixed yet.

It's kind of bad practice to disable HV for the whole app or activity, but I'm going to try to disable it for a single reveal view. Will post updates here.

**Comment by shliama** [comment]
@liufuxin I've found a problem in CircularReveal library, it was enabling hardware acceleration for API 17, when clipPath() works with hardware acceleration only from API 18 [http://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported]

I've included that lib as local module and made all needed fixes. For now, I've pushed these changes in the separate branch named <hardware_acceleration_fix>. So you can pull/include/use it for now.
By the way, it work not that smooth with HA disabled :(

I'm going to create pull-request to that library, and when/if it accepted, I'll update master branch too.
